services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    volumes:
      - postgresApp:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  backend_chatting:
    image: node:23-alpine
    container_name: backend_chatting
    working_dir: /app
    volumes:
      - ./backend/app-chatting:/app
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - NEST_PORT=${NEST_PORT}
    entrypoint: ["sh", "./entrypoint.sh"]
    depends_on:
      - postgres
  frontend_chatting:
    image: node:23-alpine
    container_name: frontend_chatting
    working_dir: /app
    volumes:
      - ./frontend/vue-chat:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_NEST_BACKEND_URL=${NEST_BACKEND_URL}
    entrypoint: ["sh", "./entrypoint.sh"]
    depends_on:
      - postgres
      - backend_chatting

  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    depends_on:
      - postgres

volumes:
  postgresApp:
